hackathon/config/routes.rb
Rails.application.routes.draw do
  resources :applicants
  resources :positions
  resources :languages
  resources :statuses
  resources :recruiters

  root 'static_pages#index'
  get 'login' => 'static_pages#login'
  get 'performance' => 'performance#index'
  get 'dashboard' => 'performance#dashboard'

end

hackathon/app/models/language.rb
class Language < ActiveRecord::Base
	has_many :applicant_languages
	has_many :applicant, through: :applicant_languages
end

hackathon/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
    len = Language.all.count
    @counts = Array.new(len)
    (1..len).each do |i|
        @counts[i-1] = Language.find(i).applicant.count
    end
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
    @applicants = @language.applicant
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:name)
    end
end

hackathon/app/helpers/languages_helper.rb
module LanguagesHelper
end

hackathon/app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Add language" , :class => "btn bg-green", :style=> "background-color:#6db33f!important;" %>
  </div>
<% end %>

hackathon/app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form' %>

<h4><%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %></h4>

hackathon/app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">View programming skills</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <!-- <div class="btn-group">
            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-wrench"></i></button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </div> -->
        </div>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-hover dataTable" id="skillTable">
              <thead>
                <tr>
                    <th>Name</th>
                    <th>No of Candidates</th>
                    <th style="width:5%;">Show</th>
                </tr>
              </thead>

              <tbody>
                  <% @languages.each_with_index do |language, k| %>
                    <tr>
                      <td><%= language.name %></td>
                      <td><%= @counts[k] %></td>
                      <td><center><%= link_to language do %><span class="fa fa-eye fa-1x"></span><% end %></center></td>
                    </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= button_to 'New Language', new_language_path, class: 'btn btn-primary', type: 'button', method: :get %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

hackathon/app/views/languages/new.html.erb
<div class="row">
  <div class="col-md-12">
<center>
    <h2><b>New Language</b></h2>
          <!-- <div class="btn-group">
            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-wrench"></i></button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </div> -->
    <%= render 'form' %>
    <h4><%= link_to 'Back', languages_path %></h4>

</center>
</div>
</div>

hackathon/app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">People who knows <%= @language.name %></h3>
          </div>
          <div class="box-body table-responsive">
            <div class="row">
              <div class="col-md-12">
                <table class="table table-bordered table-hover" id="appTable">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Position Applied</th>
                      <th>Age</th>
                      <th>Location</th>
                      <th>Gpa</th>
                      <th>Exp</th>
                      <th>Status</th>
                      <th style="width:5%;">Show</th>
                      <th style="width:4%;">Edit</th>
                      <th style="width:5%;">Destroy</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @applicants.each do |applicant| %>
                      <tr>
                        <td><%= applicant.name %></td>
                        <td><%= applicant.position.name %></td>
                        <td><%= applicant.age %></td>
                        <td><%= applicant.location %></td>
                        <td><%= applicant.gpa %></td>
                        <td><%= applicant.exp %></td>
                        <td><%= applicant.statuses.name %></td>
                        <td><center><%= link_to applicant do %><span class="fa fa-eye fa-1x"></span><% end %></center></td>
                        <td><center><%= link_to edit_applicant_path(applicant) do %><span class="fa fa-edit fa-1x"></span><% end %></center></td>
                        <td><center><%= link_to applicant, method: :delete, data: { confirm: 'Are you sure to remove this applicant?' }  do %><span class="fa fa-trash fa-1x"></span><% end %></center></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
    </div>
</div>
<div class ="row">
    <div class="col-md-12">
        <center>
       <!-- <h4><%= link_to 'Edit', edit_language_path(@language) %> |
       <%= link_to 'Back', languages_path %></h4> -->
       </center>
   </div>
</div>