hackathon/config/routes.rb
Rails.application.routes.draw do
  resources :applicants
  resources :positions
  resources :languages
  resources :statuses
  resources :recruiters

  root 'static_pages#index'
  get 'login' => 'static_pages#login'
  get 'performance' => 'performance#index'
  get 'dashboard' => 'performance#dashboard'

end

hackathon/app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
	has_many :applicant

  def rate
    apps = self.applicant
    accepted = 0
    responded = 0
    apps.each do |app, key|
      if app.statuses.last.id == 1
        puts 'no'
        responded = responded + 1
      elsif app.statuses.last.id == 5
        puts 'yes'
        accepted = accepted + 1
      end
    end
    (accepted.to_f / (accepted.to_f + responded.to_f)) * 100
  end
end

hackathon/app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  before_action :set_recruiter, only: [:show, :edit, :update, :destroy]

  # GET /recruiters
  # GET /recruiters.json
  def index
    @recruiters = Recruiter.all
    len = Recruiter.all.count
    @counts = Array.new(len)
    (1..len).each do |i|
        @counts[i-1] = Recruiter.find(i).applicant.count
    end
  end

  # GET /recruiters/1
  # GET /recruiters/1.json
  def show
      @applicants = @recruiter.applicant
  end

  # GET /recruiters/new
  def new
    @recruiter = Recruiter.new
  end

  # GET /recruiters/1/edit
  def edit
  end

  # POST /recruiters
  # POST /recruiters.json
  def create
    @recruiter = Recruiter.new(recruiter_params)

    respond_to do |format|
      if @recruiter.save
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully created.' }
        format.json { render :show, status: :created, location: @recruiter }
      else
        format.html { render :new }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recruiters/1
  # PATCH/PUT /recruiters/1.json
  def update
    respond_to do |format|
      if @recruiter.update(recruiter_params)
        format.html { redirect_to @recruiter, notice: 'Recruiter was successfully updated.' }
        format.json { render :show, status: :ok, location: @recruiter }
      else
        format.html { render :edit }
        format.json { render json: @recruiter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruiters/1
  # DELETE /recruiters/1.json
  def destroy
    @recruiter.destroy
    respond_to do |format|
      format.html { redirect_to recruiters_url, notice: 'Recruiter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recruiter
      @recruiter = Recruiter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recruiter_params
      params.require(:recruiter).permit(:name)
    end
end

hackathon/app/helpers/recruiters_helper.rb
module RecruitersHelper
end

hackathon/app/views/recruiters/_form.html.erb
<%= form_for(@recruiter) do |f| %>
  <% if @recruiter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recruiter.errors.count, "error") %> prohibited this recruiter from being saved:</h2>

      <ul>
      <% @recruiter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Add Recruiter" , :class => "btn bg-green", :style=> "background-color:#6db33f!important;" %>
  </div>
<% end %>

hackathon/app/views/recruiters/edit.html.erb
<h1>Editing Recruiter</h1>

<%= render 'form' %>

<%= link_to 'Show', @recruiter %> |
<%= link_to 'Back', recruiters_path %>

hackathon/app/views/recruiters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">View recruiters</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <!-- <div class="btn-group">
            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-wrench"></i></button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </div> -->
        </div>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-hover dataTable" id="referTable">
              <thead>
                <tr>
                    <th>Name</th>
                    <th>No of Referrals</th>
                    <th>Performance Rating</th>
                    <th style="width:5%;">Show</th>
                    <th style="width:4%;">Edit</th>
                    <th style="width:5%;">Delete</th>
                </tr>
                </thead>

                <tbody>
                <% @recruiters.each_with_index do |recruiter, k| %>
                      <tr>
                        <td><%= recruiter.name %></td>
                        <td><%= @counts[k] %></td>
                        <td><%= recruiter.rate.round(2) %></td>
                      <td><center><%= link_to recruiter do %><span class="fa fa-eye fa-1x"></span><% end %></center></td>
                      <td><center><%= link_to edit_recruiter_path(recruiter) do %><span class="fa fa-edit fa-1x"></span><% end %></center></td>
                      <td><center><%= link_to recruiter, method: :delete, data: { confirm: 'Are you sure?' }  do %><span class="fa fa-trash fa-1x"></span><% end %></center></td>
                    </tr>
                <% end %>
              </tbody>
            </table>

            <br>

            <%= button_to 'New recruiter', new_recruiter_path, class: 'btn btn-primary', type: 'button', method: :get %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

hackathon/app/views/recruiters/new.html.erb
<div class="row">
  <div class="col-md-12">
<center>
    <h2><b>New Recruiter</b></h2>
          <!-- <div class="btn-group">
            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-wrench"></i></button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </div> -->
    <%= render 'form' %>
    <h4><%= link_to 'Back', recruiters_path %></h4>

</center>
</div>
</div>

hackathon/app/views/recruiters/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="row">
      <div class="col-sm-2">
        <%= image_tag("empty-profile.png", size:"150x150", alt: "Edit Entry", class: "img-responsive")%>
      </div>
      <div class="col-sm-10">
        <h3>
          <strong><%= @recruiter.name %></strong>
        </h3>
        <h6>Recruitment Specialist</h6>
        <br><br>
        <h4>
          Success Rate: <b><%= @recruiter.rate.floor %>%</b>
        </h4>
      </div>
    </div>
  </div>
</div>
<br>
<div class="row">
  <div class="col-xs-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Referred applicants</h3>
      </div>
      <div class="box-body table-responsive">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-hover" id="appTable">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Position Applied</th>
                  <th>Age</th>
                  <th>Location</th>
                  <th>Gpa</th>
                  <th>Exp</th>
                  <th>Status</th>
                  <th style="width:5%;">Show</th>
                  <th style="width:4%;">Edit</th>
                  <th style="width:5%;">Destroy</th>
                </tr>
              </thead>

              <tbody>
                <% @applicants.each do |applicant| %>
                  <tr>
                    <td><%= applicant.name %></td>
                    <td><%= applicant.position.name %></td>
                    <td><%= applicant.age %></td>
                    <td><%= applicant.location %></td>
                    <td><%= applicant.gpa %></td>
                    <td><%= applicant.exp %></td>
                    <td><%= applicant.statuses.last.name %></td>
                    <td><center><%= link_to applicant do %><span class="fa fa-eye fa-1x"></span><% end %></center></td>
                    <td><center><%= link_to edit_applicant_path(applicant) do %><span class="fa fa-edit fa-1x"></span><% end %></center></td>
                    <td><center><%= link_to applicant, method: :delete, data: { confirm: 'Are you sure to remove this applicant?' }  do %><span class="fa fa-trash fa-1x"></span><% end %></center></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
</div>
  <h4><center>
    <!-- <%= link_to 'Edit', edit_recruiter_path(@recruiter) %> |
    <%= link_to 'Back', recruiters_path %> -->
    </center></h4>

  </div>
  </div>