hackathon/config/routes.rb
Rails.application.routes.draw do
  resources :applicants
  resources :positions
  resources :languages
  resources :statuses
  resources :recruiters

  root 'static_pages#index'
  get 'login' => 'static_pages#login'
  get 'performance' => 'performance#index'
  get 'dashboard' => 'performance#dashboard'

end

hackathon/app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">
        <%= image_tag("logo-01.png", size:"50x40")%>
    </span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">Cogni<b>COP</b></span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-dashboard navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="/assets/user2-160x160.jpg" class="user-image" alt="User Image"/>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">RecruiterA</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image" />
              <p>
                  Human Resources Person
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Body -->
            <!-- <li class="user-body">
              <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
              </div>
              <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
              </div>
            </li> -->
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="<%= login_path %>" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
        <!-- <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li> -->
      </ul>
    </div>
  </nav>
</header>

hackathon/app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">NAVIGATION BAR</li>
        <!-- Optionally, you can add icons to the links -->
      <li class="<% if controller.controller_name == 'performance' and controller.action_name == 'dashboard' %>active<% end %>"><a href="<%= dashboard_path %>"><i class='fa fa-link'></i> <span>Dashboard</span></a></li>
      <li class="treeview <% if controller.controller_name == 'applicants' %>active<% end %>">
        <a href="#"><i class='fa fa-users'></i> <span>Applicants</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li><%= link_to "View", applicants_path %></li>
            <li><%= link_to "Add", new_applicant_path %></li>
        </ul>
      </li>
      <li class="treeview <% if controller.controller_name == 'positions' %>active<% end %>">
        <a href="#"><i class='fa fa-street-view'></i> <span>Positions</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><%= link_to "View", positions_path %></li>
          <li><%= link_to "Add", new_position_path %></li>
        </ul>
      </li>
      <li class="treeview <% if controller.controller_name == 'applicants' %>languages<% end %>">
        <a href="#"><i class='fa fa-language'></i> <span>Skills</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li><%= link_to "View", languages_path %></li>
            <li><%= link_to "Add", new_language_path %></li>
        </ul>
      </li>
      <li class="treeview <% if controller.controller_name == 'statuses' %>active<% end %>">
        <a href="#"><i class='fa fa-cubes'></i> <span>Statuses</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li><%= link_to "View", statuses_path %></li>
        </ul>
      </li>
      <li class="treeview <% if controller.controller_name == 'recruiters' %>active<% end %>">
        <a href="#"><i class='fa fa-user-secret'></i> <span>Recruiters</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li><%= link_to "View", recruiters_path %></li>
            <li><%= link_to "Add", new_recruiter_path %></li>
        </ul>
      </li>
      <li class="<% if controller.controller_name == 'performance' and controller.action_name == 'index' %>active<% end %>"><a href="<%= performance_path %>"><i class='fa fa-bar-chart'></i> <span>Recruitment Performance</span></a></li>
      <!-- <li><a href="#"><i class='fa fa-link'></i> <span>Exit</span></a></li> -->
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

hackathon/app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
          <link rel="icon" type="image/png" href="/assets/logo.png">
  <title>

        CogniCop</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<% if current_page?('/') or current_page?('/login') %>
    <body class="skin-blue layout-top-nav hold-transition fixed <%= params[:controller].parameterize %> <%= action_name %>">
<% else %>
    <body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
<% end %>
    <div class="wrapper">

      <% unless current_page?('/') or current_page?('/login') %>
          <%= render partial: 'layouts/admin_lte_2_header' %>
          <%= render partial: 'layouts/admin_lte_2_sidebar' %>
      <% end %>
    <!-- Content Wrapper. Contains page content -->
    <% if current_page?('/')%>
    <div class="content-wrapper" style="padding-top:0px;background-color:#ececec;">
    <% elsif current_page?('/login') %>
    <div class="content-wrapper container-intro" style="padding-top:0px;background-color:#ececec;">
    <% else %>
    <div class="content-wrapper">
    <% end %>
      <!-- Content Header (Page header) -->
      <!-- <section class="content-header">
        <h1>
          Page Header
          <small>Optional description</small>
        </h1>
        <ol class="breadcrumb">
          <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
          <li class="active">Here</li>
        </ol>
      </section> -->

      <!-- Main content -->
      <% if current_page?('/') %>
      <section class="content content-landing">
      <% else %>
      <section class="content">
      <% end %>
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        We don't just track. We capture.
      </div>
      <strong>Copyright &copy; 2016 <a href="#">University of the Philippines Center for Student Innovations</a>.</strong> All rights reserved.
    </footer>

    <!-- <aside class="control-sidebar control-sidebar-dark">
      <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab" aria-expanded="true"><i class="fa fa-home"></i></a></li>
        <li class=""><a href="#control-sidebar-settings-tab" data-toggle="tab" aria-expanded="false"><i class="fa fa-gears"></i></a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="control-sidebar-home-tab">
          <h3 class="control-sidebar-heading">Recent Activity</h3>
          <ul class="control-sidebar-menu">
            <li>
              <a href="javascript::;">
                <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                <div class="menu-info">
                  <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                  <p>Will be 23 on April 24th</p>
                </div>
              </a>
            </li>
          </ul>

          <h3 class="control-sidebar-heading">Tasks Progress</h3>
          <ul class="control-sidebar-menu">
            <li>
              <a href="javascript::;">
                <h4 class="control-sidebar-subheading">
                  Custom Template Design
                  <span class="label label-danger pull-right">70%</span>
                </h4>
                <div class="progress progress-xxs">
                  <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                </div>
              </a>
            </li>
          </ul>

        </div>
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <div class="tab-pane" id="control-sidebar-settings-tab">
          <form method="post">
            <h3 class="control-sidebar-heading">General Settings</h3>
            <div class="form-group">
              <label class="control-sidebar-subheading">
                Report panel usage
                <input type="checkbox" class="pull-right" checked="">
              </label>
              <p>
                Some information about this general settings option
              </p>
            </div>
          </form>
        </div>
      </div>
    </aside>

    <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div> -->

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript">
    <% if controller.action_name == 'login' %>
      $('body').addClass('sidebar-collapse');
    <% end %>
  </script>
</body>
</html>

hackathon/app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AdminLTE 2 | Log in</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Admin</b>LTE</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

hackathon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackathon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>