hackathon/config/routes.rb
Rails.application.routes.draw do
  resources :applicants
  resources :positions
  resources :languages
  resources :statuses
  resources :recruiters

  root 'static_pages#index'
  get 'login' => 'static_pages#login'
  get 'performance' => 'performance#index'
  get 'dashboard' => 'performance#dashboard'

end

hackathon/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
    len = Status.all.count
    @counts = Array.new(len)
    (1..len).each do |i|
        @counts[i-1] = Status.find(i).applicants.count
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
      @applicants = @status.applicants
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name)
    end
end

hackathon/app/helpers/statuses_helper.rb
module StatusesHelper
end

hackathon/app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
      <%= f.submit "Add Status" , :class => "btn bg-green", :style=> "background-color:#6db33f!important;" %>
  </div>
<% end %>

hackathon/app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

hackathon/app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">View recruitment status/stages</h3>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <!-- <div class="btn-group">
            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-wrench"></i></button>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </div> -->
          <!-- <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button> -->
        </div>
      </div>
      <div class="box-body">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-bordered table-hover dataTable" id="statTable">
              <thead>
                <tr>
                    <th>Name</th>
                    <th>Count</th>
                    <th style="width:5%;">Show</th>
                  </tr>
                </thead>

                <tbody>
                    <% @statuses.each_with_index do |status, k| %>
                      <tr>
                        <td><%= status.name %></td>
                        <td><%= @counts[k] %></td>
                        <td><center><%= link_to status do %><span class="fa fa-eye fa-1x"></span><% end %></center></td>
                      </tr>
                  <% end %>
              </tbody>
            </table>

            <br>

            <%= button_to 'New status', new_status_path, class: 'btn btn-primary', type: 'button', method: :get %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

hackathon/app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

hackathon/app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-md-12">
        <!-- <center>
        <h3>Status:
          <strong>
            <%= @status.name %>
          </strong>
        </h3>
        </center> -->
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title">Applicants who reached stage <%= @status.name %></h3>
          </div>
          <div class="box-body table-responsive">
            <div class="row">
              <div class="col-md-12">
                <table class="table table-bordered table-hover" id="appTable">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Age</th>
                      <th>Location</th>
                      <th>Gpa</th>
                      <th>Exp</th>
                      <th style="width:5%;">Show</th>
                      <th style="width:4%;">Edit</th>
                      <th style="width:5%;">Destroy</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @applicants.each do |applicant| %>
                      <tr>
                        <td><%= applicant.name %></td>
                        <td><%= applicant.age %></td>
                        <td><%= applicant.location %></td>
                        <td><%= applicant.gpa %></td>
                        <td><%= applicant.exp %></td>
                        <td><center><%= link_to applicant do %><span class="fa fa-eye fa-1x"></span><% end %></center></td>
                        <td><center><%= link_to edit_applicant_path(applicant) do %><span class="fa fa-edit fa-1x"></span><% end %></center></td>
                        <td><center><%= link_to applicant, method: :delete, data: { confirm: 'Are you sure to remove this applicant?' }  do %><span class="fa fa-trash fa-1x"></span><% end %></center></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
</div>
<div class ="row">
     <div class="col-md-12">
         <center>
        <!-- <h4><%= link_to 'Edit', edit_status_path(@status) %> |
        <%= link_to 'Back', statuses_path %></h4> -->
        </center>
    </div>
</div>